package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdeCliente generated by hbm2java
 */
@Entity
@Table(name="ade_cliente"
    ,schema="public"
)
public class AdeCliente  implements java.io.Serializable {


     private int idAdeCliente;
     private Cliente cliente;
     private Usuario usuario;
     private String descrip;
     private Date fecha;
     private String estadoPago;
     private String estadoCobro;
     private Double monto;

    public AdeCliente() {
    }

    public AdeCliente(Cliente cliente, Usuario usuario, String descrip, Date fecha, String estadoPago, String estadoCobro, Double monto) {
       this.cliente = cliente;
       this.usuario = usuario;
       this.descrip = descrip;
       this.fecha = fecha;
       this.estadoPago = estadoPago;
       this.estadoCobro = estadoCobro;
       this.monto = monto;
    }
   
     @SequenceGenerator(name="generator", sequenceName="ade_cliente_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_ade_cliente", nullable=false)
    public int getIdAdeCliente() {
        return this.idAdeCliente;
    }
    
    public void setIdAdeCliente(int idAdeCliente) {
        this.idAdeCliente = idAdeCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_id")
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="descrip", length=200)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="estado_pago", length=20)
    public String getEstadoPago() {
        return this.estadoPago;
    }
    
    public void setEstadoPago(String estadoPago) {
        this.estadoPago = estadoPago;
    }

    
    @Column(name="estado_cobro", length=20)
    public String getEstadoCobro() {
        return this.estadoCobro;
    }
    
    public void setEstadoCobro(String estadoCobro) {
        this.estadoCobro = estadoCobro;
    }

    
    @Column(name="monto", precision=17, scale=17)
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }




}


