package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Camion generated by hbm2java
 */
@Entity
@Table(name="camion"
    ,schema="public"
)
public class Camion  implements java.io.Serializable {


     private String chapaCamion;
     private Carreta carreta;
     private Chofer chofer;
     private Propietario propietario;
     private TipoCamion tipoCamion;
     private String marca;
     private int anho;
     private String color;
     private String modelo;
     private String departamento;
     private Date fechaVencimiento;
     private int peso;
     private String estado;
     private Set recibos = new HashSet(0);
     private Set items = new HashSet(0);
     private Set viaticos = new HashSet(0);
     private Set exCamions = new HashSet(0);
     private Set adelantoChofers = new HashSet(0);
     private Set valeVarioses = new HashSet(0);
     private Set valeCombustibles = new HashSet(0);
     private Set ordenDeCargas = new HashSet(0);
     private Set creditos = new HashSet(0);
     private Set itemcs = new HashSet(0);

    public Camion() {
    }

	
    public Camion(String chapaCamion, Carreta carreta, Chofer chofer, Propietario propietario, TipoCamion tipoCamion, String marca, int anho, String color, String modelo, Date fechaVencimiento, int peso) {
        this.chapaCamion = chapaCamion;
        this.carreta = carreta;
        this.chofer = chofer;
        this.propietario = propietario;
        this.tipoCamion = tipoCamion;
        this.marca = marca;
        this.anho = anho;
        this.color = color;
        this.modelo = modelo;
        this.fechaVencimiento = fechaVencimiento;
        this.peso = peso;
    }
    public Camion(String chapaCamion, Carreta carreta, Chofer chofer, Propietario propietario, TipoCamion tipoCamion, String marca, int anho, String color, String modelo, String departamento, Date fechaVencimiento, int peso, String estado, Set recibos, Set items, Set viaticos, Set exCamions, Set adelantoChofers, Set valeVarioses, Set valeCombustibles, Set ordenDeCargas, Set creditos, Set itemcs) {
       this.chapaCamion = chapaCamion;
       this.carreta = carreta;
       this.chofer = chofer;
       this.propietario = propietario;
       this.tipoCamion = tipoCamion;
       this.marca = marca;
       this.anho = anho;
       this.color = color;
       this.modelo = modelo;
       this.departamento = departamento;
       this.fechaVencimiento = fechaVencimiento;
       this.peso = peso;
       this.estado = estado;
       this.recibos = recibos;
       this.items = items;
       this.viaticos = viaticos;
       this.exCamions = exCamions;
       this.adelantoChofers = adelantoChofers;
       this.valeVarioses = valeVarioses;
       this.valeCombustibles = valeCombustibles;
       this.ordenDeCargas = ordenDeCargas;
       this.creditos = creditos;
       this.itemcs = itemcs;
    }
   
     @Id 

    
    @Column(name="chapa_camion", nullable=false, length=6)
    public String getChapaCamion() {
        return this.chapaCamion;
    }
    
    public void setChapaCamion(String chapaCamion) {
        this.chapaCamion = chapaCamion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="carreta_chapa_carreta", nullable=false)
    public Carreta getCarreta() {
        return this.carreta;
    }
    
    public void setCarreta(Carreta carreta) {
        this.carreta = carreta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="chofer_id_chofer", nullable=false)
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="propietario_id_propietario", nullable=false)
    public Propietario getPropietario() {
        return this.propietario;
    }
    
    public void setPropietario(Propietario propietario) {
        this.propietario = propietario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_camion_id_tipo_camion", nullable=false)
    public TipoCamion getTipoCamion() {
        return this.tipoCamion;
    }
    
    public void setTipoCamion(TipoCamion tipoCamion) {
        this.tipoCamion = tipoCamion;
    }

    
    @Column(name="marca", nullable=false, length=30)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="anho", nullable=false)
    public int getAnho() {
        return this.anho;
    }
    
    public void setAnho(int anho) {
        this.anho = anho;
    }

    
    @Column(name="color", nullable=false, length=30)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="modelo", nullable=false, length=30)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    
    @Column(name="departamento", length=30)
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_vencimiento", nullable=false, length=13)
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

    
    @Column(name="peso", nullable=false)
    public int getPeso() {
        return this.peso;
    }
    
    public void setPeso(int peso) {
        this.peso = peso;
    }
        @Column(name="estado", length=30)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="camion")
    public Set getRecibos() {
        return this.recibos;
    }
    
    public void setRecibos(Set recibos) {
        this.recibos = recibos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="camion")
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="camion")
    public Set getViaticos() {
        return this.viaticos;
    }
    
    public void setViaticos(Set viaticos) {
        this.viaticos = viaticos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="camion")
    public Set getExCamions() {
        return this.exCamions;
    }
    
    public void setExCamions(Set exCamions) {
        this.exCamions = exCamions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="camion")
    public Set getAdelantoChofers() {
        return this.adelantoChofers;
    }
    
    public void setAdelantoChofers(Set adelantoChofers) {
        this.adelantoChofers = adelantoChofers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="camion")
    public Set getValeVarioses() {
        return this.valeVarioses;
    }
    
    public void setValeVarioses(Set valeVarioses) {
        this.valeVarioses = valeVarioses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="camion")
    public Set getValeCombustibles() {
        return this.valeCombustibles;
    }
    
    public void setValeCombustibles(Set valeCombustibles) {
        this.valeCombustibles = valeCombustibles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="camion")
    public Set getOrdenDeCargas() {
        return this.ordenDeCargas;
    }
    
    public void setOrdenDeCargas(Set ordenDeCargas) {
        this.ordenDeCargas = ordenDeCargas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="camion")
    public Set getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Set creditos) {
        this.creditos = creditos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="camion")
    public Set getItemcs() {
        return this.itemcs;
    }
    
    public void setItemcs(Set itemcs) {
        this.itemcs = itemcs;
    }




}


