package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carreta generated by hbm2java
 */
@Entity
@Table(name="carreta"
    ,schema="public"
)
public class Carreta  implements java.io.Serializable {


     private String chapaCarreta;
     private TipoCarreta tipoCarreta;
     private String color;
     private String marca;
     private int anho;
     private String departamento;
     private Date fechaDinatran;
     private Set camions = new HashSet(0);

    public Carreta() {
    }

	
    public Carreta(String chapaCarreta, TipoCarreta tipoCarreta, String color, String marca, int anho, Date fechaDinatran) {
        this.chapaCarreta = chapaCarreta;
        this.tipoCarreta = tipoCarreta;
        this.color = color;
        this.marca = marca;
        this.anho = anho;
        this.fechaDinatran = fechaDinatran;
    }
    public Carreta(String chapaCarreta, TipoCarreta tipoCarreta, String color, String marca, int anho, String departamento, Date fechaDinatran, Set camions) {
       this.chapaCarreta = chapaCarreta;
       this.tipoCarreta = tipoCarreta;
       this.color = color;
       this.marca = marca;
       this.anho = anho;
       this.departamento = departamento;
       this.fechaDinatran = fechaDinatran;
       this.camions = camions;
    }
   
     @Id 

    
    @Column(name="chapa_carreta", nullable=false, length=6)
    public String getChapaCarreta() {
        return this.chapaCarreta;
    }
    
    public void setChapaCarreta(String chapaCarreta) {
        this.chapaCarreta = chapaCarreta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_carreta_id_tipo_carreta", nullable=false)
    public TipoCarreta getTipoCarreta() {
        return this.tipoCarreta;
    }
    
    public void setTipoCarreta(TipoCarreta tipoCarreta) {
        this.tipoCarreta = tipoCarreta;
    }

    
    @Column(name="color", nullable=false, length=30)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="marca", nullable=false, length=30)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="anho", nullable=false)
    public int getAnho() {
        return this.anho;
    }
    
    public void setAnho(int anho) {
        this.anho = anho;
    }

    
    @Column(name="departamento", length=50)
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_dinatran", nullable=false, length=13)
    public Date getFechaDinatran() {
        return this.fechaDinatran;
    }
    
    public void setFechaDinatran(Date fechaDinatran) {
        this.fechaDinatran = fechaDinatran;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="carreta")
    public Set getCamions() {
        return this.camions;
    }
    
    public void setCamions(Set camions) {
        this.camions = camions;
    }




}


