package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,schema="public"
)
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String nombre;
     private String ruc;
     private String direccion;
     private String correo;
     private String telefono;
     private Set seguros = new HashSet(0);
     private Set precioFletes = new HashSet(0);
     private Set ordenDeCargas = new HashSet(0);
     private Set pagoFletes = new HashSet(0);
     private Set productos = new HashSet(0);
     private Set tolerancias = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nombre, String ruc) {
        this.nombre = nombre;
        this.ruc = ruc;
    }
    public Cliente(String nombre, String ruc, String direccion, String correo, String telefono, Set seguros, Set precioFletes, Set ordenDeCargas, Set pagoFletes, Set productos, Set tolerancias) {
       this.nombre = nombre;
       this.ruc = ruc;
       this.direccion = direccion;
       this.correo = correo;
       this.telefono = telefono;
       this.seguros = seguros;
       this.precioFletes = precioFletes;
       this.ordenDeCargas = ordenDeCargas;
       this.pagoFletes = pagoFletes;
       this.productos = productos;
       this.tolerancias = tolerancias;
    }
   
     @SequenceGenerator(name="generator", sequenceName="cliente_id_cliente_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_cliente", nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ruc", nullable=false, length=30)
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    
    @Column(name="direccion", length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="correo", length=50)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="telefono", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getSeguros() {
        return this.seguros;
    }
    
    public void setSeguros(Set seguros) {
        this.seguros = seguros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getPrecioFletes() {
        return this.precioFletes;
    }
    
    public void setPrecioFletes(Set precioFletes) {
        this.precioFletes = precioFletes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getOrdenDeCargas() {
        return this.ordenDeCargas;
    }
    
    public void setOrdenDeCargas(Set ordenDeCargas) {
        this.ordenDeCargas = ordenDeCargas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getPagoFletes() {
        return this.pagoFletes;
    }
    
    public void setPagoFletes(Set pagoFletes) {
        this.pagoFletes = pagoFletes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getTolerancias() {
        return this.tolerancias;
    }
    
    public void setTolerancias(Set tolerancias) {
        this.tolerancias = tolerancias;
    }




}


