package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CombustibleContra generated by hbm2java
 */
@Entity
@Table(name="combustible_contra"
    ,schema="public"
)
public class CombustibleContra  implements java.io.Serializable {


     private int id;
     private Contrasenha contrasenha;
     private ValeCombustible valeCombustible;

    public CombustibleContra() {
    }

    public CombustibleContra(Contrasenha contrasenha, ValeCombustible valeCombustible) {
       this.contrasenha = contrasenha;
       this.valeCombustible = valeCombustible;
    }
   
     @SequenceGenerator(name="generator", sequenceName="combustible_contra_id_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contrasenha_id_contrasenha", nullable=false)
    public Contrasenha getContrasenha() {
        return this.contrasenha;
    }
    
    public void setContrasenha(Contrasenha contrasenha) {
        this.contrasenha = contrasenha;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vale_combustible_id_vale_combustible", nullable=false)
    public ValeCombustible getValeCombustible() {
        return this.valeCombustible;
    }
    
    public void setValeCombustible(ValeCombustible valeCombustible) {
        this.valeCombustible = valeCombustible;
    }




}


