package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrasenha generated by hbm2java
 */
@Entity
@Table(name="contrasenha"
    ,schema="public"
)
public class Contrasenha  implements java.io.Serializable {


     private int idContrasenha;
     private Usuario usuario;
     private Viaje viaje;
     private Date fecha;
     private String descripcion;
     private double saldo;
     private double combustible;
     private double viatico;
     private Set combustibleContras = new HashSet(0);
     private Set viaticoContras = new HashSet(0);

    public Contrasenha() {
    }

	
    public Contrasenha(Usuario usuario, Viaje viaje, Date fecha, double saldo, double combustible, double viatico) {
        this.usuario = usuario;
        this.viaje = viaje;
        this.fecha = fecha;
        this.saldo = saldo;
        this.combustible = combustible;
        this.viatico = viatico;
    }
    public Contrasenha(Usuario usuario, Viaje viaje, Date fecha, String descripcion, double saldo, double combustible, double viatico, Set combustibleContras, Set viaticoContras) {
       this.usuario = usuario;
       this.viaje = viaje;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.saldo = saldo;
       this.combustible = combustible;
       this.viatico = viatico;
       this.combustibleContras = combustibleContras;
       this.viaticoContras = viaticoContras;
    }
   
     @SequenceGenerator(name="generator", sequenceName="contrasenha_id_contrasenha_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_contrasenha", nullable=false)
    public int getIdContrasenha() {
        return this.idContrasenha;
    }
    
    public void setIdContrasenha(int idContrasenha) {
        this.idContrasenha = idContrasenha;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="viaje_id_viaje", nullable=false)
    public Viaje getViaje() {
        return this.viaje;
    }
    
    public void setViaje(Viaje viaje) {
        this.viaje = viaje;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="saldo", nullable=false, precision=17, scale=17)
    public double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(double saldo) {
        this.saldo = saldo;
    }

    
    @Column(name="combustible", nullable=false, precision=17, scale=17)
    public double getCombustible() {
        return this.combustible;
    }
    
    public void setCombustible(double combustible) {
        this.combustible = combustible;
    }

    
    @Column(name="viatico", nullable=false, precision=17, scale=17)
    public double getViatico() {
        return this.viatico;
    }
    
    public void setViatico(double viatico) {
        this.viatico = viatico;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrasenha")
    public Set getCombustibleContras() {
        return this.combustibleContras;
    }
    
    public void setCombustibleContras(Set combustibleContras) {
        this.combustibleContras = combustibleContras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrasenha")
    public Set getViaticoContras() {
        return this.viaticoContras;
    }
    
    public void setViaticoContras(Set viaticoContras) {
        this.viaticoContras = viaticoContras;
    }




}


