package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Credito generated by hbm2java
 */
@Entity
@Table(name="credito"
    ,schema="public"
)
public class Credito  implements java.io.Serializable {


     private int idCredito;
     private Camion camion;
     private Usuario usuario;
     private Date fecha;
     private Date fechaVencimiento;
     private int monto;
     private String descripcion;
     private String estadoCobro;

    public Credito() {
    }

	
    public Credito(Camion camion, Usuario usuario, Date fecha, Date fechaVencimiento, int monto, String estadoCobro) {
        this.camion = camion;
        this.usuario = usuario;
        this.fecha = fecha;
        this.fechaVencimiento = fechaVencimiento;
        this.monto = monto;
        this.estadoCobro = estadoCobro;
    }
    public Credito(Camion camion, Usuario usuario, Date fecha, Date fechaVencimiento, int monto, String descripcion, String estadoCobro) {
       this.camion = camion;
       this.usuario = usuario;
       this.fecha = fecha;
       this.fechaVencimiento = fechaVencimiento;
       this.monto = monto;
       this.descripcion = descripcion;
       this.estadoCobro = estadoCobro;
    }
   
     @SequenceGenerator(name="generator", sequenceName="credito_id_credito_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_credito", nullable=false)
    public int getIdCredito() {
        return this.idCredito;
    }
    
    public void setIdCredito(int idCredito) {
        this.idCredito = idCredito;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="camion_chapa_camion", nullable=false)
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_vencimiento", nullable=false, length=13)
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

    
    @Column(name="monto", nullable=false)
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="estado_cobro", nullable=false, length=20)
    public String getEstadoCobro() {
        return this.estadoCobro;
    }
    
    public void setEstadoCobro(String estadoCobro) {
        this.estadoCobro = estadoCobro;
    }




}


