package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DetExtracto generated by hbm2java
 */
@Entity
@Table(name="det_extracto"
    ,schema="public"
)
public class DetExtracto  implements java.io.Serializable {


     private int idDet;
     private Extracto extracto;
     private Item item;
     private double pasivo;
     private double activo;
     private String descrip;
     private Set extractoSumiclis = new HashSet(0);
     private Set detSumis = new HashSet(0);
     private Set extractoSumis = new HashSet(0);

    public DetExtracto() {
    }

    public DetExtracto(Extracto extracto, Item item, double pasivo, double activo, String descrip, Set extractoSumiclis, Set detSumis, Set extractoSumis) {
       this.extracto = extracto;
       this.item = item;
       this.pasivo = pasivo;
       this.activo = activo;
       this.descrip = descrip;
       this.extractoSumiclis = extractoSumiclis;
       this.detSumis = detSumis;
       this.extractoSumis = extractoSumis;
    }
   
     @SequenceGenerator(name="generator", sequenceName="credito_id_credito_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_det", nullable=false)
    public int getIdDet() {
        return this.idDet;
    }
    
    public void setIdDet(int idDet) {
        this.idDet = idDet;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="extracto_id_liquidacion", nullable=false)
    public Extracto getExtracto() {
        return this.extracto;
    }
    
    public void setExtracto(Extracto extracto) {
        this.extracto = extracto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_id_item", nullable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

    
    @Column(name="pasivo", nullable=false, precision=17, scale=17)
    public double getPasivo() {
        return this.pasivo;
    }
    
    public void setPasivo(double pasivo) {
        this.pasivo = pasivo;
    }

    
    @Column(name="activo", nullable=false, precision=17, scale=17)
    public double getActivo() {
        return this.activo;
    }
    
    public void setActivo(double activo) {
        this.activo = activo;
    }

    
    @Column(name="descrip", nullable=false, length=100)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="detExtracto")
    public Set getExtractoSumiclis() {
        return this.extractoSumiclis;
    }
    
    public void setExtractoSumiclis(Set extractoSumiclis) {
        this.extractoSumiclis = extractoSumiclis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="detExtracto")
    public Set getDetSumis() {
        return this.detSumis;
    }
    
    public void setDetSumis(Set detSumis) {
        this.detSumis = detSumis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="detExtracto")
    public Set getExtractoSumis() {
        return this.extractoSumis;
    }
    
    public void setExtractoSumis(Set extractoSumis) {
        this.extractoSumis = extractoSumis;
    }


}


