package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetExtractoc generated by hbm2java
 */
@Entity
@Table(name="det_extractoc"
    ,schema="public"
)
public class DetExtractoc  implements java.io.Serializable {


     private int idDet;
     private Extractoc extractoc;
     private Itemc itemc;
     private double pasivo;
     private double activo;
     private String descrip;

    public DetExtractoc() {
    }

    public DetExtractoc(int idDet, Extractoc extractoc, Itemc itemc, double pasivo, double activo, String descrip) {
       this.idDet = idDet;
       this.extractoc = extractoc;
       this.itemc = itemc;
       this.pasivo = pasivo;
       this.activo = activo;
       this.descrip = descrip;
    }
   
     @Id 

    
    @Column(name="id_det", nullable=false)
    public int getIdDet() {
        return this.idDet;
    }
    
    public void setIdDet(int idDet) {
        this.idDet = idDet;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="extractoc_id", nullable=false)
    public Extractoc getExtractoc() {
        return this.extractoc;
    }
    
    public void setExtractoc(Extractoc extractoc) {
        this.extractoc = extractoc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="itemc_id_item", nullable=false)
    public Itemc getItemc() {
        return this.itemc;
    }
    
    public void setItemc(Itemc itemc) {
        this.itemc = itemc;
    }

    
    @Column(name="pasivo", nullable=false, precision=17, scale=17)
    public double getPasivo() {
        return this.pasivo;
    }
    
    public void setPasivo(double pasivo) {
        this.pasivo = pasivo;
    }

    
    @Column(name="activo", nullable=false, precision=17, scale=17)
    public double getActivo() {
        return this.activo;
    }
    
    public void setActivo(double activo) {
        this.activo = activo;
    }

    
    @Column(name="descrip", nullable=false, length=100)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }




}


