package model;
// Generated 22/10/2021 08:40:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import model.AdeCliente;
import model.PagoFlete;

/**
 * DetPagoAde generated by hbm2java
 */
@Entity
@Table(name="det_pago_ade"
    ,schema="public"
)
public class DetPagoAde  implements java.io.Serializable {


     private int idDetPagoAde;
     private AdeCliente adeCliente;
     private PagoFlete pagoFlete;
     private Double monto;
     private Double descuento;
     private Double totalMonto;

    public DetPagoAde() {
    }

	
    public DetPagoAde(int idDetPagoAde) {
        this.idDetPagoAde = idDetPagoAde;
    }
    public DetPagoAde(int idDetPagoAde, AdeCliente adeCliente, PagoFlete pagoFlete, Double monto, Double descuento, Double totalMonto) {
       this.idDetPagoAde = idDetPagoAde;
       this.adeCliente = adeCliente;
       this.pagoFlete = pagoFlete;
       this.monto = monto;
       this.descuento = descuento;
       this.totalMonto = totalMonto;
    }
   
     @Id 

    
    @Column(name="id_det_pago_ade", unique=true, nullable=false)
    public int getIdDetPagoAde() {
        return this.idDetPagoAde;
    }
    
    public void setIdDetPagoAde(int idDetPagoAde) {
        this.idDetPagoAde = idDetPagoAde;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="adelanto_id")
    public AdeCliente getAdeCliente() {
        return this.adeCliente;
    }
    
    public void setAdeCliente(AdeCliente adeCliente) {
        this.adeCliente = adeCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pago_id")
    public PagoFlete getPagoFlete() {
        return this.pagoFlete;
    }
    
    public void setPagoFlete(PagoFlete pagoFlete) {
        this.pagoFlete = pagoFlete;
    }

    
    @Column(name="monto", precision=17, scale=17)
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }

    
    @Column(name="descuento", precision=17, scale=17)
    public Double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Double descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="total_monto", precision=17, scale=17)
    public Double getTotalMonto() {
        return this.totalMonto;
    }
    
    public void setTotalMonto(Double totalMonto) {
        this.totalMonto = totalMonto;
    }




}


