package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DetPagoFlete generated by hbm2java
 */
@Entity
@Table(name="det_pago_flete"
    ,schema="public"
)
public class DetPagoFlete  implements java.io.Serializable {


     private int idDetPagoFlete;
     private PagoFlete pagoFlete;
     private Viaje viaje;
     private double monto;
     private double descuento;
     private double totalMonto;

    public DetPagoFlete() {
    }

    public DetPagoFlete(PagoFlete pagoFlete, Viaje viaje, double monto, double descuento, double totalMonto) {
       this.pagoFlete = pagoFlete;
       this.viaje = viaje;
       this.monto = monto;
       this.descuento = descuento;
       this.totalMonto = totalMonto;
    }
   
     @SequenceGenerator(name="generator", sequenceName="det_pago_flete_id_det_pago_flete_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_det_pago_flete", nullable=false)
    public int getIdDetPagoFlete() {
        return this.idDetPagoFlete;
    }
    
    public void setIdDetPagoFlete(int idDetPagoFlete) {
        this.idDetPagoFlete = idDetPagoFlete;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pago_flete_id_pago_flete", nullable=false)
    public PagoFlete getPagoFlete() {
        return this.pagoFlete;
    }
    
    public void setPagoFlete(PagoFlete pagoFlete) {
        this.pagoFlete = pagoFlete;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="viaje_id_viaje", nullable=false)
    public Viaje getViaje() {
        return this.viaje;
    }
    
    public void setViaje(Viaje viaje) {
        this.viaje = viaje;
    }

    
    @Column(name="monto", nullable=false, precision=17, scale=17)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    
    @Column(name="descuento", nullable=false, precision=17, scale=17)
    public double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(double descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="total_monto", nullable=false, precision=17, scale=17)
    public double getTotalMonto() {
        return this.totalMonto;
    }
    
    public void setTotalMonto(double totalMonto) {
        this.totalMonto = totalMonto;
    }




}


