package model;
// Generated 22/10/2021 08:40:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import model.PagoFlete;
import model.SumiCliente;

/**
 * DetPagoSumi generated by hbm2java
 */
@Entity
@Table(name="det_pago_sumi"
    ,schema="public"
)
public class DetPagoSumi  implements java.io.Serializable {


     private int idPagoDet;
     private PagoFlete pagoFlete;
     private SumiCliente sumiCliente;
     private Double monto;
     private Double descuento;
     private Double totalMonto;

    public DetPagoSumi() {
    }

	
    public DetPagoSumi(int idPagoDet) {
        this.idPagoDet = idPagoDet;
    }
    public DetPagoSumi(int idPagoDet, PagoFlete pagoFlete, SumiCliente sumiCliente, Double monto, Double descuento, Double totalMonto) {
       this.idPagoDet = idPagoDet;
       this.pagoFlete = pagoFlete;
       this.sumiCliente = sumiCliente;
       this.monto = monto;
       this.descuento = descuento;
       this.totalMonto = totalMonto;
    }
   
     @Id 

    
    @Column(name="id_pago_det", unique=true, nullable=false)
    public int getIdPagoDet() {
        return this.idPagoDet;
    }
    
    public void setIdPagoDet(int idPagoDet) {
        this.idPagoDet = idPagoDet;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pago_id")
    public PagoFlete getPagoFlete() {
        return this.pagoFlete;
    }
    
    public void setPagoFlete(PagoFlete pagoFlete) {
        this.pagoFlete = pagoFlete;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sumicli_id")
    public SumiCliente getSumiCliente() {
        return this.sumiCliente;
    }
    
    public void setSumiCliente(SumiCliente sumiCliente) {
        this.sumiCliente = sumiCliente;
    }

    
    @Column(name="monto", precision=17, scale=17)
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }

    
    @Column(name="descuento", precision=17, scale=17)
    public Double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Double descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="total_monto", precision=17, scale=17)
    public Double getTotalMonto() {
        return this.totalMonto;
    }
    
    public void setTotalMonto(Double totalMonto) {
        this.totalMonto = totalMonto;
    }




}


