package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetSumi generated by hbm2java
 */
@Entity
@Table(name="det_sumi"
    ,schema="public"
)
public class DetSumi  implements java.io.Serializable {


     private int idDetSumi;
     private DetExtracto detExtracto;
     private Suministro suministro;
     private Double monto;
     private String descripcion;

    public DetSumi() {
    }

	
    public DetSumi(int idDetSumi) {
        this.idDetSumi = idDetSumi;
    }
    public DetSumi(int idDetSumi, DetExtracto detExtracto, Suministro suministro, Double monto, String descripcion) {
       this.idDetSumi = idDetSumi;
       this.detExtracto = detExtracto;
       this.suministro = suministro;
       this.monto = monto;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="id_det_sumi", nullable=false)
    public int getIdDetSumi() {
        return this.idDetSumi;
    }
    
    public void setIdDetSumi(int idDetSumi) {
        this.idDetSumi = idDetSumi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="det_extracto_id")
    public DetExtracto getDetExtracto() {
        return this.detExtracto;
    }
    
    public void setDetExtracto(DetExtracto detExtracto) {
        this.detExtracto = detExtracto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_suministro")
    public Suministro getSuministro() {
        return this.suministro;
    }
    
    public void setSuministro(Suministro suministro) {
        this.suministro = suministro;
    }

    
    @Column(name="monto", precision=17, scale=17)
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


