package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Extractoc generated by hbm2java
 */
@Entity
@Table(name="extractoc"
    ,schema="public"
)
public class Extractoc  implements java.io.Serializable {


     private int id;
     private Chofer chofer;
     private Usuario usuario;
     private Date fecha;
     private double monto;
     private String descripcion;
     private String estado;
     private Set detExtractocs = new HashSet(0);

    public Extractoc() {
    }

	
    public Extractoc(int id, Chofer chofer, Usuario usuario, Date fecha, double monto, String descripcion, String estado) {
        this.id = id;
        this.chofer = chofer;
        this.usuario = usuario;
        this.fecha = fecha;
        this.monto = monto;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public Extractoc(int id, Chofer chofer, Usuario usuario, Date fecha, double monto, String descripcion, String estado, Set detExtractocs) {
       this.id = id;
       this.chofer = chofer;
       this.usuario = usuario;
       this.fecha = fecha;
       this.monto = monto;
       this.descripcion = descripcion;
       this.estado = estado;
       this.detExtractocs = detExtractocs;
    }
   
     @Id 

    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="chofer_id_chofer", nullable=false)
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="monto", nullable=false, precision=17, scale=17)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="extractoc")
    public Set getDetExtractocs() {
        return this.detExtractocs;
    }
    
    public void setDetExtractocs(Set detExtractocs) {
        this.detExtractocs = detExtractocs;
    }




}


