package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Extracto generated by hbm2java
 */
@Entity
@Table(name="extracto"
    ,schema="public"
)
public class Extracto  implements java.io.Serializable {


     private int idLiquidacion;
     private Propietario propietario;
     private Usuario usuario;
     private Date fecha;
     private Date fechaPago;
     private double monto;
     private String descripcion;
     private String estado;
     private Set exCamions = new HashSet(0);
     private Set detExtractos = new HashSet(0);

    public Extracto() {
    }

	
    public Extracto(Propietario propietario, Usuario usuario, Date fecha, Date fechaPago, double monto, String descripcion, String estado) {
        this.propietario = propietario;
        this.usuario = usuario;
        this.fecha = fecha;
        this.fechaPago = fechaPago;
        this.monto = monto;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public Extracto(Propietario propietario, Usuario usuario, Date fecha, Date fechaPago, double monto, String descripcion, String estado, Set exCamions, Set detExtractos) {
       this.propietario = propietario;
       this.usuario = usuario;
       this.fecha = fecha;
       this.fechaPago = fechaPago;
       this.monto = monto;
       this.descripcion = descripcion;
       this.estado = estado;
       this.exCamions = exCamions;
       this.detExtractos = detExtractos;
    }
   
     @SequenceGenerator(name="generator", sequenceName="extracto_id_liquidacion_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_liquidacion", nullable=false)
    public int getIdLiquidacion() {
        return this.idLiquidacion;
    }
    
    public void setIdLiquidacion(int idLiquidacion) {
        this.idLiquidacion = idLiquidacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="propietario_id_propietario", nullable=false)
    public Propietario getPropietario() {
        return this.propietario;
    }
    
    public void setPropietario(Propietario propietario) {
        this.propietario = propietario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_pago", nullable=false, length=13)
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }

    
    @Column(name="monto", nullable=false, precision=17, scale=17)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="extracto")
    public Set getExCamions() {
        return this.exCamions;
    }
    
    public void setExCamions(Set exCamions) {
        this.exCamions = exCamions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="extracto")
    public Set getDetExtractos() {
        return this.detExtractos;
    }
    
    public void setDetExtractos(Set detExtractos) {
        this.detExtractos = detExtractos;
    }




}


