package model;
// Generated 17/11/2021 10:56:24 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExtractoSumicli generated by hbm2java
 */
@Entity
@Table(name="extracto_sumicli"
    ,schema="public"
)
public class ExtractoSumicli  implements java.io.Serializable {


     private int idExSumicli;
     private DetExtracto detExtracto;
     private SumiCliente sumiCliente;
     private String descrip;
     private Double monto;

    public ExtractoSumicli() {
    }

	
    public ExtractoSumicli(int idExSumicli) {
        this.idExSumicli = idExSumicli;
    }
    public ExtractoSumicli(int idExSumicli, DetExtracto detExtracto, SumiCliente sumiCliente, String descrip, Double monto) {
       this.idExSumicli = idExSumicli;
       this.detExtracto = detExtracto;
       this.sumiCliente = sumiCliente;
       this.descrip = descrip;
       this.monto = monto;
    }
   
     @Id 

    
    @Column(name="id_ex_sumicli", unique=true, nullable=false)
    public int getIdExSumicli() {
        return this.idExSumicli;
    }
    
    public void setIdExSumicli(int idExSumicli) {
        this.idExSumicli = idExSumicli;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_det_extracto")
    public DetExtracto getDetExtracto() {
        return this.detExtracto;
    }
    
    public void setDetExtracto(DetExtracto detExtracto) {
        this.detExtracto = detExtracto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sumicli")
    public SumiCliente getSumiCliente() {
        return this.sumiCliente;
    }
    
    public void setSumiCliente(SumiCliente sumiCliente) {
        this.sumiCliente = sumiCliente;
    }

    
    @Column(name="descrip", length=100)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    
    @Column(name="monto", precision=17, scale=17)
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }




}


