package model;
// Generated 17/11/2021 10:56:24 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExtractoSumi generated by hbm2java
 */
@Entity
@Table(name="extracto_sumi"
    ,schema="public"
)
public class ExtractoSumi  implements java.io.Serializable {


     private int idExSumi;
     private DetExtracto detExtracto;
     private Suministro suministro;
     private String descrip;
     private Double monto;

    public ExtractoSumi() {
    }

	
    public ExtractoSumi(int idExSumi) {
        this.idExSumi = idExSumi;
    }
    public ExtractoSumi(int idExSumi, DetExtracto detExtracto, Suministro suministro, String descrip, Double monto) {
       this.idExSumi = idExSumi;
       this.detExtracto = detExtracto;
       this.suministro = suministro;
       this.descrip = descrip;
       this.monto = monto;
    }
   
     @Id 

    
    @Column(name="id_ex_sumi", unique=true, nullable=false)
    public int getIdExSumi() {
        return this.idExSumi;
    }
    
    public void setIdExSumi(int idExSumi) {
        this.idExSumi = idExSumi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_det_extracto")
    public DetExtracto getDetExtracto() {
        return this.detExtracto;
    }
    
    public void setDetExtracto(DetExtracto detExtracto) {
        this.detExtracto = detExtracto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_suministro")
    public Suministro getSuministro() {
        return this.suministro;
    }
    
    public void setSuministro(Suministro suministro) {
        this.suministro = suministro;
    }

    
    @Column(name="descrip", length=100)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    
    @Column(name="monto", precision=17, scale=17)
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }




}


