package model;
// Generated 23/11/2021 15:14:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="item"
    ,schema="public"
)
public class Item  implements java.io.Serializable {


     private int idItem;
     private Camion camion;
     private TipoItem tipoItem;
     private double pasivo;
     private double activo;
     private String descrip;
     private int cod;
     private String estado;
     private Date fecha;
     private Set detExtractos = new HashSet(0);
     private OrdenDeCarga ordenDeCarga;
     private Extracto extracto;

    public Item() {
    }

	
    public Item(Camion camion, TipoItem tipoItem, double pasivo, double activo, String descrip, int cod, String estado, Date fecha) {
        this.camion = camion;
        this.tipoItem = tipoItem;
        this.pasivo = pasivo;
        this.activo = activo;
        this.descrip = descrip;
        this.cod = cod;
        this.estado = estado;
        this.fecha = fecha;
    }
    public Item(Camion camion, Extracto extracto, OrdenDeCarga ordenDeCarga, TipoItem tipoItem, double pasivo, double activo, String descrip, int cod, String estado, Date fecha, Set detExtractos) {
       this.camion = camion;
       this.tipoItem = tipoItem;
       this.pasivo = pasivo;
       this.activo = activo;
       this.descrip = descrip;
       this.cod = cod;
       this.estado = estado;
       this.fecha = fecha;
       this.detExtractos = detExtractos;
       this.ordenDeCarga = ordenDeCarga;
       this.extracto = extracto;
    }
   
     @SequenceGenerator(name="generator", sequenceName="extractoc_id_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_item", nullable=false)
    public int getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(int idItem) {
        this.idItem = idItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="camion_chapa_camion", nullable=false)
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="extracto_id")
    public Extracto getExtracto() {
        return this.extracto;
    }
    
    public void setExtracto(Extracto extracto) {
        this.extracto = extracto;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orden_id")
    public OrdenDeCarga getOrdenDeCarga() {
        return this.ordenDeCarga;
    }
    
    public void setOrdenDeCarga(OrdenDeCarga ordenDeCarga) {
        this.ordenDeCarga = ordenDeCarga;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_item_id_tipo", nullable=false)
    public TipoItem getTipoItem() {
        return this.tipoItem;
    }
    
    public void setTipoItem(TipoItem tipoItem) {
        this.tipoItem = tipoItem;
    }

    
    @Column(name="pasivo", nullable=false, precision=17, scale=17)
    public double getPasivo() {
        return this.pasivo;
    }
    
    public void setPasivo(double pasivo) {
        this.pasivo = pasivo;
    }

    
    @Column(name="activo", nullable=false, precision=17, scale=17)
    public double getActivo() {
        return this.activo;
    }
    
    public void setActivo(double activo) {
        this.activo = activo;
    }

    
    @Column(name="descrip", nullable=false, length=100)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    
    @Column(name="cod", nullable=false)
    public int getCod() {
        return this.cod;
    }
    
    public void setCod(int cod) {
        this.cod = cod;
    }

    
    @Column(name="estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="item")
    public Set getDetExtractos() {
        return this.detExtractos;
    }
    
    public void setDetExtractos(Set detExtractos) {
        this.detExtractos = detExtractos;
    }




}


