package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Itemc generated by hbm2java
 */
@Entity
@Table(name="itemc"
    ,schema="public"
)
public class Itemc  implements java.io.Serializable {


     private int idItem;
     private Camion camion;
     private Chofer chofer;
     private TipoItemc tipoItemc;
     private double pasivo;
     private double activo;
     private String descrip;
     private int cod;
     private String estado;
     private Date fecha;
     private Set detExtractocs = new HashSet(0);

    public Itemc() {
    }

	
    public Itemc(int idItem, Camion camion, Chofer chofer, TipoItemc tipoItemc, double pasivo, double activo, String descrip, int cod, String estado, Date fecha) {
        this.idItem = idItem;
        this.camion = camion;
        this.chofer = chofer;
        this.tipoItemc = tipoItemc;
        this.pasivo = pasivo;
        this.activo = activo;
        this.descrip = descrip;
        this.cod = cod;
        this.estado = estado;
        this.fecha = fecha;
    }
    public Itemc(int idItem, Camion camion, Chofer chofer, TipoItemc tipoItemc, double pasivo, double activo, String descrip, int cod, String estado, Date fecha, Set detExtractocs) {
       this.idItem = idItem;
       this.camion = camion;
       this.chofer = chofer;
       this.tipoItemc = tipoItemc;
       this.pasivo = pasivo;
       this.activo = activo;
       this.descrip = descrip;
       this.cod = cod;
       this.estado = estado;
       this.fecha = fecha;
       this.detExtractocs = detExtractocs;
    }
   
     @Id 

    
    @Column(name="id_item", nullable=false)
    public int getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(int idItem) {
        this.idItem = idItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="camion_chapa_camion", nullable=false)
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="chofer_id_chofer", nullable=false)
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_itemc_id_tipo", nullable=false)
    public TipoItemc getTipoItemc() {
        return this.tipoItemc;
    }
    
    public void setTipoItemc(TipoItemc tipoItemc) {
        this.tipoItemc = tipoItemc;
    }

    
    @Column(name="pasivo", nullable=false, precision=17, scale=17)
    public double getPasivo() {
        return this.pasivo;
    }
    
    public void setPasivo(double pasivo) {
        this.pasivo = pasivo;
    }

    
    @Column(name="activo", nullable=false, precision=17, scale=17)
    public double getActivo() {
        return this.activo;
    }
    
    public void setActivo(double activo) {
        this.activo = activo;
    }

    
    @Column(name="descrip", nullable=false, length=100)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    
    @Column(name="cod", nullable=false)
    public int getCod() {
        return this.cod;
    }
    
    public void setCod(int cod) {
        this.cod = cod;
    }

    
    @Column(name="estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemc")
    public Set getDetExtractocs() {
        return this.detExtractocs;
    }
    
    public void setDetExtractocs(Set detExtractocs) {
        this.detExtractocs = detExtractocs;
    }




}


