package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PagoFlete generated by hbm2java
 */
@Entity
@Table(name="pago_flete"
    ,schema="public"
)
public class PagoFlete  implements java.io.Serializable {


     private int idPagoFlete;
     private Cliente cliente;
     private Usuario usuario;
     private Date fecha;
     private String nroLiq;
     private double monto;
     private double iva;
     private double montoTotal;
     private double montoIva;
     private String descripcion;
     private String estado;
     private String ivacom;
     private String retencion;
     private Set detPagoFletes = new HashSet(0);

    public PagoFlete() {
    }

	
    public PagoFlete(Cliente cliente, Usuario usuario, Date fecha, String nroLiq, double monto, double iva, double montoTotal, double montoIva, String descripcion, String estado, String ivacom, String retencion) {
        this.cliente = cliente;
        this.usuario = usuario;
        this.fecha = fecha;
        this.nroLiq = nroLiq;
        this.monto = monto;
        this.iva = iva;
        this.montoTotal = montoTotal;
        this.montoIva = montoIva;
        this.descripcion = descripcion;
        this.estado = estado;
        this.ivacom=ivacom;
        this.retencion=retencion;
    }
    public PagoFlete(Cliente cliente, Usuario usuario, Date fecha, String nroLiq, double monto, double iva, double montoTotal, double montoIva, String descripcion, String estado,String ivacom, String retencion, Set detPagoFletes) {
       this.cliente = cliente;
       this.usuario = usuario;
       this.fecha = fecha;
       this.nroLiq = nroLiq;
       this.monto = monto;
       this.iva = iva;
       this.montoTotal = montoTotal;
       this.montoIva = montoIva;
       this.descripcion = descripcion;
       this.estado = estado;
       this.ivacom=ivacom;
       this.retencion=retencion;
       this.detPagoFletes = detPagoFletes;
       
    }
   
     @SequenceGenerator(name="generator", sequenceName="pago_flete_id_pago_flete_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_pago_flete", nullable=false)
    public int getIdPagoFlete() {
        return this.idPagoFlete;
    }
    
    public void setIdPagoFlete(int idPagoFlete) {
        this.idPagoFlete = idPagoFlete;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_id_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="nro_liq", nullable=false, length=20)
    public String getNroLiq() {
        return this.nroLiq;
    }
    
    public void setNroLiq(String nroLiq) {
        this.nroLiq = nroLiq;
    }

    
    @Column(name="monto", nullable=false, precision=17, scale=17)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    
    @Column(name="iva", nullable=false, precision=17, scale=17)
    public double getIva() {
        return this.iva;
    }
    
    public void setIva(double iva) {
        this.iva = iva;
    }

    
    @Column(name="monto_total", nullable=false, precision=17, scale=17)
    public double getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(double montoTotal) {
        this.montoTotal = montoTotal;
    }

    
    @Column(name="monto_iva", nullable=false, precision=17, scale=17)
    public double getMontoIva() {
        return this.montoIva;
    }
    
    public void setMontoIva(double montoIva) {
        this.montoIva = montoIva;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="estado", nullable=false, length=30)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getIvacom() {
        return ivacom;
    }

    public void setIvacom(String ivacom) {
        this.ivacom = ivacom;
    }

    public String getRetencion() {
        return retencion;
    }

    public void setRetencion(String retencion) {
        this.retencion = retencion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pagoFlete")
    public Set getDetPagoFletes() {
        return this.detPagoFletes;
    }
    
    public void setDetPagoFletes(Set detPagoFletes) {
        this.detPagoFletes = detPagoFletes;
    }




}


