package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PagoCombustible generated by hbm2java
 */
@Entity
@Table(name="pago_combustible"
    ,schema="public"
)
public class PagoCombustible  implements java.io.Serializable {


     private int idPagoCombustible;
     private Proveedor proveedor;
     private Usuario usuario;
     private Date fecha;
     private String descripcion;
     private String estado;
     private double total;
     private Set detallePagoCombs = new HashSet(0);

    public PagoCombustible() {
    }

	
    public PagoCombustible(Proveedor proveedor, Usuario usuario, Date fecha, String descripcion, String estado, double total) {
        this.proveedor = proveedor;
        this.usuario = usuario;
        this.fecha = fecha;
        this.descripcion = descripcion;
        this.estado = estado;
        this.total = total;
    }
    public PagoCombustible(Proveedor proveedor, Usuario usuario, Date fecha, String descripcion, String estado, double total, Set detallePagoCombs) {
       this.proveedor = proveedor;
       this.usuario = usuario;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.estado = estado;
       this.total = total;
       this.detallePagoCombs = detallePagoCombs;
    }
   
     @SequenceGenerator(name="generator", sequenceName="orden_de_carga_id_orden_de_carga_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_pago_combustible", nullable=false)
    public int getIdPagoCombustible() {
        return this.idPagoCombustible;
    }
    
    public void setIdPagoCombustible(int idPagoCombustible) {
        this.idPagoCombustible = idPagoCombustible;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proveedor_id_proveedor", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="estado", nullable=false, length=30)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="total", nullable=false, precision=17, scale=17)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pagoCombustible")
    public Set getDetallePagoCombs() {
        return this.detallePagoCombs;
    }
    
    public void setDetallePagoCombs(Set detallePagoCombs) {
        this.detallePagoCombs = detallePagoCombs;
    }




}


