package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PagoSuministro generated by hbm2java
 */
@Entity
@Table(name="pago_suministro"
    ,schema="public"
)
public class PagoSuministro  implements java.io.Serializable {


     private int idPagosumi;
     private ProveeCliente proveeCliente;
     private Usuario usuario;
     private String descrip;
     private String factura;
     private Double montoSumi;
     private Double montoAdelanto;
     private Double saldo;
     private Double montoPagar;
     private Date fecha;
     private String estado;
     private Set pagoSumiDets = new HashSet(0);
     private Set pagoAdeDets = new HashSet(0);

    public PagoSuministro() {
    }

    public PagoSuministro(ProveeCliente proveeCliente, Usuario usuario, String descrip, String factura, Double montoSumi, Double montoAdelanto, Double saldo, Double montoPagar, Date fecha, String estado, Set pagoSumiDets, Set pagoAdeDets) {
       this.proveeCliente = proveeCliente;
       this.usuario = usuario;
       this.descrip = descrip;
       this.factura = factura;
       this.montoSumi = montoSumi;
       this.montoAdelanto = montoAdelanto;
       this.saldo = saldo;
       this.montoPagar = montoPagar;
       this.fecha = fecha;
       this.estado = estado;
       this.pagoSumiDets = pagoSumiDets;
       this.pagoAdeDets = pagoAdeDets;
    }
   
     @SequenceGenerator(name="generator", sequenceName="pagosumi_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_pagosumi", nullable=false)
    public int getIdPagosumi() {
        return this.idPagosumi;
    }
    
    public void setIdPagosumi(int idPagosumi) {
        this.idPagosumi = idPagosumi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proveedor_id")
    public ProveeCliente getProveeCliente() {
        return this.proveeCliente;
    }
    
    public void setProveeCliente(ProveeCliente proveeCliente) {
        this.proveeCliente = proveeCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="descrip", length=100)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    
    @Column(name="factura", length=50)
    public String getFactura() {
        return this.factura;
    }
    
    public void setFactura(String factura) {
        this.factura = factura;
    }

    
    @Column(name="monto_sumi", precision=17, scale=17)
    public Double getMontoSumi() {
        return this.montoSumi;
    }
    
    public void setMontoSumi(Double montoSumi) {
        this.montoSumi = montoSumi;
    }

    
    @Column(name="monto_adelanto", precision=17, scale=17)
    public Double getMontoAdelanto() {
        return this.montoAdelanto;
    }
    
    public void setMontoAdelanto(Double montoAdelanto) {
        this.montoAdelanto = montoAdelanto;
    }

    
    @Column(name="saldo", precision=17, scale=17)
    public Double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Double saldo) {
        this.saldo = saldo;
    }

    
    @Column(name="monto_pagar", precision=17, scale=17)
    public Double getMontoPagar() {
        return this.montoPagar;
    }
    
    public void setMontoPagar(Double montoPagar) {
        this.montoPagar = montoPagar;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="estado", length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pagoSuministro")
    public Set getPagoSumiDets() {
        return this.pagoSumiDets;
    }
    
    public void setPagoSumiDets(Set pagoSumiDets) {
        this.pagoSumiDets = pagoSumiDets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pagoSuministro")
    public Set getPagoAdeDets() {
        return this.pagoAdeDets;
    }
    
    public void setPagoAdeDets(Set pagoAdeDets) {
        this.pagoAdeDets = pagoAdeDets;
    }




}


