package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PagoSumiDet generated by hbm2java
 */
@Entity
@Table(name="pago_sumi_det"
    ,schema="public"
)
public class PagoSumiDet  implements java.io.Serializable {


     private int idDetalle;
     private PagoSuministro pagoSuministro;
     private Suministro suministro;
     private Double monto;
     private Double cant;
     private Double precioComb;

    public PagoSumiDet() {
    }

    public PagoSumiDet(PagoSuministro pagoSuministro, Suministro suministro, Double monto, Double cant, Double precioComb) {
       this.pagoSuministro = pagoSuministro;
       this.suministro = suministro;
       this.monto = monto;
       this.cant = cant;
       this.precioComb = precioComb;
    }
   
     @SequenceGenerator(name="generator", sequenceName="detsumi_Seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_detalle", nullable=false)
    public int getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(int idDetalle) {
        this.idDetalle = idDetalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pago_sumi_id")
    public PagoSuministro getPagoSuministro() {
        return this.pagoSuministro;
    }
    
    public void setPagoSuministro(PagoSuministro pagoSuministro) {
        this.pagoSuministro = pagoSuministro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="suministro_id")
    public Suministro getSuministro() {
        return this.suministro;
    }
    
    public void setSuministro(Suministro suministro) {
        this.suministro = suministro;
    }

    
    @Column(name="monto", precision=17, scale=17)
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }

    
    @Column(name="cant", precision=17, scale=17)
    public Double getCant() {
        return this.cant;
    }
    
    public void setCant(Double cant) {
        this.cant = cant;
    }

    
    @Column(name="precio_comb", precision=17, scale=17)
    public Double getPrecioComb() {
        return this.precioComb;
    }
    
    public void setPrecioComb(Double precioComb) {
        this.precioComb = precioComb;
    }




}


