package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PrecioFlete generated by hbm2java
 */
@Entity
@Table(name="precio_flete"
    ,schema="public"
)
public class PrecioFlete  implements java.io.Serializable {


     private int idPrecioFlete;
     private Cliente cliente;
     private UnidadDestino unidadDestino;
     private UnidadOrigen unidadOrigen;
     private Usuario usuario;
     private double precioPago;
     private String descripcion;
     private double precioCobro;
     private String estado;
     private double precioiva;
     private Set viajes = new HashSet(0);

    public PrecioFlete() {
    }

	
    public PrecioFlete(Cliente cliente, UnidadDestino unidadDestino, UnidadOrigen unidadOrigen, Usuario usuario, double precioPago, String descripcion, double precioCobro, String estado, double precioiva) {
        this.cliente = cliente;
        this.unidadDestino = unidadDestino;
        this.unidadOrigen = unidadOrigen;
        this.usuario = usuario;
        this.precioPago = precioPago;
        this.descripcion = descripcion;
        this.precioCobro = precioCobro;
        this.estado = estado;
        this.precioiva=precioiva;
    }
    public PrecioFlete(Cliente cliente, UnidadDestino unidadDestino, UnidadOrigen unidadOrigen, Usuario usuario, double precioPago, String descripcion, double precioCobro, String estado, double precioiva, Set viajes) {
       this.cliente = cliente;
       this.unidadDestino = unidadDestino;
       this.unidadOrigen = unidadOrigen;
       this.usuario = usuario;
       this.precioPago = precioPago;
       this.descripcion = descripcion;
       this.precioCobro = precioCobro;
       this.estado = estado;
       this.precioiva=precioiva;
       this.viajes = viajes;
    }
   
     @SequenceGenerator(name="generator", sequenceName="precio_flete_id_precio_flete_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_precio_flete", nullable=false)
    public int getIdPrecioFlete() {
        return this.idPrecioFlete;
    }
    
    public void setIdPrecioFlete(int idPrecioFlete) {
        this.idPrecioFlete = idPrecioFlete;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_id_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unidad_destino_id_unidad_destino", nullable=false)
    public UnidadDestino getUnidadDestino() {
        return this.unidadDestino;
    }
    
    public void setUnidadDestino(UnidadDestino unidadDestino) {
        this.unidadDestino = unidadDestino;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unidad_origen_id_unidad_origen", nullable=false)
    public UnidadOrigen getUnidadOrigen() {
        return this.unidadOrigen;
    }
    
    public void setUnidadOrigen(UnidadOrigen unidadOrigen) {
        this.unidadOrigen = unidadOrigen;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="precio_pago", nullable=false, precision=17, scale=17)
    public double getPrecioPago() {
        return this.precioPago;
    }
    
    public void setPrecioPago(double precioPago) {
        this.precioPago = precioPago;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="precio_cobro", nullable=false, precision=17, scale=17)
    public double getPrecioCobro() {
        return this.precioCobro;
    }
    
    public void setPrecioCobro(double precioCobro) {
        this.precioCobro = precioCobro;
    }

    
    @Column(name="estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    @Column(name="precioiva", nullable=false, precision=17, scale=17)
    public double getPrecioiva() {
        return precioiva;
    }

    public void setPrecioiva(double precioiva) {
        this.precioiva = precioiva;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="precioFlete")
    public Set getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set viajes) {
        this.viajes = viajes;
    }




}


