package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PrecioComb generated by hbm2java
 */
@Entity
@Table(name="precio_comb"
    ,schema="public"
)
public class PrecioComb  implements java.io.Serializable {


     private int idPrecioComb;
     private Proveedor proveedor;
     private TipoCombustible tipoCombustible;
     private int monto;
     private String estado;

    public PrecioComb() {
    }

    public PrecioComb(Proveedor proveedor, TipoCombustible tipoCombustible, int monto, String estado) {
       this.proveedor = proveedor;
       this.tipoCombustible = tipoCombustible;
       this.monto = monto;
       this.estado = estado;
    }
   
     @SequenceGenerator(name="generator", sequenceName="precio_comb_id_precio_comb_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_precio_comb", nullable=false)
    public int getIdPrecioComb() {
        return this.idPrecioComb;
    }
    
    public void setIdPrecioComb(int idPrecioComb) {
        this.idPrecioComb = idPrecioComb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proveedor_id_proveedor", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_combustible_id_tipo_combustible", nullable=false)
    public TipoCombustible getTipoCombustible() {
        return this.tipoCombustible;
    }
    
    public void setTipoCombustible(TipoCombustible tipoCombustible) {
        this.tipoCombustible = tipoCombustible;
    }

    
    @Column(name="monto", nullable=false)
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }

    
    @Column(name="estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


