package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,schema="public"
)
public class Producto  implements java.io.Serializable {


     private int idProducto;
     private Cliente cliente;
     private String nombre;
     private double precio;
     private Set ordenDeCargas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Cliente cliente, String nombre, double precio) {
        this.cliente = cliente;
        this.nombre = nombre;
        this.precio = precio;
    }
    public Producto(Cliente cliente, String nombre, double precio, Set ordenDeCargas) {
       this.cliente = cliente;
       this.nombre = nombre;
       this.precio = precio;
       this.ordenDeCargas = ordenDeCargas;
    }
   
     @SequenceGenerator(name="generator", sequenceName="producto_id_producto_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_producto", nullable=false)
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_id_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="precio", nullable=false, precision=17, scale=17)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set getOrdenDeCargas() {
        return this.ordenDeCargas;
    }
    
    public void setOrdenDeCargas(Set ordenDeCargas) {
        this.ordenDeCargas = ordenDeCargas;
    }




}


