package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="proveedor"
    ,schema="public"
)
public class Proveedor  implements java.io.Serializable {


     private int idProveedor;
     private String nombre;
     private String direccion;
     private String telefono;
     private String ruc;
     private String emblema;
     private String descripcion;
     private Set valeCombustibles = new HashSet(0);
     private Set precioCombs = new HashSet(0);
     private Set pagoCombustibles = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String nombre, String emblema) {
        this.nombre = nombre;
        this.emblema = emblema;
    }
    public Proveedor(String nombre, String direccion, String telefono, String ruc, String emblema, String descripcion, Set valeCombustibles, Set precioCombs, Set pagoCombustibles) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.ruc = ruc;
       this.emblema = emblema;
       this.descripcion = descripcion;
       this.valeCombustibles = valeCombustibles;
       this.precioCombs = precioCombs;
       this.pagoCombustibles = pagoCombustibles;
    }
   
     @SequenceGenerator(name="generator", sequenceName="proveedor_id_proveedor_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_proveedor", nullable=false)
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="direccion", length=30)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="ruc", length=30)
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    
    @Column(name="emblema", nullable=false, length=50)
    public String getEmblema() {
        return this.emblema;
    }
    
    public void setEmblema(String emblema) {
        this.emblema = emblema;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set getValeCombustibles() {
        return this.valeCombustibles;
    }
    
    public void setValeCombustibles(Set valeCombustibles) {
        this.valeCombustibles = valeCombustibles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set getPrecioCombs() {
        return this.precioCombs;
    }
    
    public void setPrecioCombs(Set precioCombs) {
        this.precioCombs = precioCombs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set getPagoCombustibles() {
        return this.pagoCombustibles;
    }
    
    public void setPagoCombustibles(Set pagoCombustibles) {
        this.pagoCombustibles = pagoCombustibles;
    }




}


