package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ProveeCliente generated by hbm2java
 */
@Entity
@Table(name="provee_cliente"
    ,schema="public"
)
public class ProveeCliente  implements java.io.Serializable {


     private int idProveecli;
     private TipoProvee tipoProvee;
     private String nombre;
     private String ruc;
     private String direccion;
     private String correo;
     private String telefono;
     private String descripcion;
     private Set adeSuministros = new HashSet(0);
     private Set unidadProvees = new HashSet(0);
     private Set pagoSuministros = new HashSet(0);

    public ProveeCliente() {
    }

    public ProveeCliente(TipoProvee tipoProvee, String nombre, String ruc, String direccion, String correo, String telefono, String descripcion, Set adeSuministros, Set unidadProvees, Set pagoSuministros) {
       this.tipoProvee = tipoProvee;
       this.nombre = nombre;
       this.ruc = ruc;
       this.direccion = direccion;
       this.correo = correo;
       this.telefono = telefono;
       this.descripcion = descripcion;
       this.adeSuministros = adeSuministros;
       this.unidadProvees = unidadProvees;
       this.pagoSuministros = pagoSuministros;
    }
   
     @SequenceGenerator(name="generator", sequenceName="provee_cliente_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_proveecli", nullable=false)
    public int getIdProveecli() {
        return this.idProveecli;
    }
    
    public void setIdProveecli(int idProveecli) {
        this.idProveecli = idProveecli;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_provee")
    public TipoProvee getTipoProvee() {
        return this.tipoProvee;
    }
    
    public void setTipoProvee(TipoProvee tipoProvee) {
        this.tipoProvee = tipoProvee;
    }

    
    @Column(name="nombre", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ruc", length=20)
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    
    @Column(name="direccion", length=60)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="correo", length=60)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="telefono", length=30)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveeCliente")
    public Set getAdeSuministros() {
        return this.adeSuministros;
    }
    
    public void setAdeSuministros(Set adeSuministros) {
        this.adeSuministros = adeSuministros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveeCliente")
    public Set getUnidadProvees() {
        return this.unidadProvees;
    }
    
    public void setUnidadProvees(Set unidadProvees) {
        this.unidadProvees = unidadProvees;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveeCliente")
    public Set getPagoSuministros() {
        return this.pagoSuministros;
    }
    
    public void setPagoSuministros(Set pagoSuministros) {
        this.pagoSuministros = pagoSuministros;
    }




}


