package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProveedorVarios generated by hbm2java
 */
@Entity
@Table(name="proveedor_varios"
    ,schema="public"
)
public class ProveedorVarios  implements java.io.Serializable {


     private int idProveedorVarios;
     private String nombre;
     private String telefono;
     private String direccion;
     private Date fechaInicio;
     private String ruc;
     private Set valeVarioses = new HashSet(0);
     private Set pagoVarioses = new HashSet(0);

    public ProveedorVarios() {
    }

	
    public ProveedorVarios(String nombre) {
        this.nombre = nombre;
    }
    public ProveedorVarios(String nombre, String telefono, String direccion, Date fechaInicio, String ruc, Set valeVarioses, Set pagoVarioses) {
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.fechaInicio = fechaInicio;
       this.ruc = ruc;
       this.valeVarioses = valeVarioses;
       this.pagoVarioses = pagoVarioses;
    }
   
     @SequenceGenerator(name="generator", sequenceName="proveedor_id_proveedor_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_proveedor_varios", nullable=false)
    public int getIdProveedorVarios() {
        return this.idProveedorVarios;
    }
    
    public void setIdProveedorVarios(int idProveedorVarios) {
        this.idProveedorVarios = idProveedorVarios;
    }

    
    @Column(name="nombre", nullable=false, length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="telefono", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="direccion", length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", length=13)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    
    @Column(name="ruc", length=50)
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedorVarios")
    public Set getValeVarioses() {
        return this.valeVarioses;
    }
    
    public void setValeVarioses(Set valeVarioses) {
        this.valeVarioses = valeVarioses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedorVarios")
    public Set getPagoVarioses() {
        return this.pagoVarioses;
    }
    
    public void setPagoVarioses(Set pagoVarioses) {
        this.pagoVarioses = pagoVarioses;
    }




}


