package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Recibo generated by hbm2java
 */
@Entity
@Table(name="recibo"
    ,schema="public"
)
public class Recibo  implements java.io.Serializable {


     private int idRecibo;
     private Camion camion;
     private double monto;
     private String descrip;
     private String estado;

    public Recibo() {
    }

    public Recibo(Camion camion, double monto, String descrip, String estado) {
       this.camion = camion;
       this.monto = monto;
       this.descrip = descrip;
       this.estado = estado;
    }
   
     @SequenceGenerator(name="generator", sequenceName="recibo_id_recibo_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_recibo", nullable=false)
    public int getIdRecibo() {
        return this.idRecibo;
    }
    
    public void setIdRecibo(int idRecibo) {
        this.idRecibo = idRecibo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="camion_chapa_camion", nullable=false)
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }

    
    @Column(name="monto", nullable=false, precision=17, scale=17)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    
    @Column(name="descrip", nullable=false, length=50)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    
    @Column(name="estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


