package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Seguro generated by hbm2java
 */
@Entity
@Table(name="seguro"
    ,schema="public"
)
public class Seguro  implements java.io.Serializable {


     private int idSeguro;
     private Cliente cliente;
     private double monto;
     private String descripcion;
     private Set viajes = new HashSet(0);

    public Seguro() {
    }

	
    public Seguro(Cliente cliente, double monto) {
        this.cliente = cliente;
        this.monto = monto;
    }
    public Seguro(Cliente cliente, double monto, String descripcion, Set viajes) {
       this.cliente = cliente;
       this.monto = monto;
       this.descripcion = descripcion;
       this.viajes = viajes;
    }
   
     @SequenceGenerator(name="generator", sequenceName="seguro_id_seguro_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_seguro", nullable=false)
    public int getIdSeguro() {
        return this.idSeguro;
    }
    
    public void setIdSeguro(int idSeguro) {
        this.idSeguro = idSeguro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_id_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="monto", nullable=false, precision=17, scale=17)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seguro")
    public Set getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set viajes) {
        this.viajes = viajes;
    }




}


