package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TipoCombustible generated by hbm2java
 */
@Entity
@Table(name="tipo_combustible"
    ,schema="public"
)
public class TipoCombustible  implements java.io.Serializable {


     private int idTipoCombustible;
     private String nombre;
     private Set valeCombustibles = new HashSet(0);
     private Set precioCombs = new HashSet(0);

    public TipoCombustible() {
    }

	
    public TipoCombustible(String nombre) {
        this.nombre = nombre;
    }
    public TipoCombustible(String nombre, Set valeCombustibles, Set precioCombs) {
       this.nombre = nombre;
       this.valeCombustibles = valeCombustibles;
       this.precioCombs = precioCombs;
    }
   
     @SequenceGenerator(name="generator", sequenceName="tipo_combustible_id_tipo_combustible_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_tipo_combustible", nullable=false)
    public int getIdTipoCombustible() {
        return this.idTipoCombustible;
    }
    
    public void setIdTipoCombustible(int idTipoCombustible) {
        this.idTipoCombustible = idTipoCombustible;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoCombustible")
    public Set getValeCombustibles() {
        return this.valeCombustibles;
    }
    
    public void setValeCombustibles(Set valeCombustibles) {
        this.valeCombustibles = valeCombustibles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoCombustible")
    public Set getPrecioCombs() {
        return this.precioCombs;
    }
    
    public void setPrecioCombs(Set precioCombs) {
        this.precioCombs = precioCombs;
    }




}


