package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoProvee generated by hbm2java
 */
@Entity
@Table(name="tipo_provee"
    ,schema="public"
)
public class TipoProvee  implements java.io.Serializable {


     private int idProvee;
     private String nombre;
     private Set proveedors = new HashSet(0);

    public TipoProvee() {
    }

	
    public TipoProvee(int idProvee) {
        this.idProvee = idProvee;
    }
    public TipoProvee(int idProvee, String nombre, Set proveedors) {
       this.idProvee = idProvee;
       this.nombre = nombre;
       this.proveedors = proveedors;
    }
   
     @Id 

    
    @Column(name="id_provee", nullable=false)
    public int getIdProvee() {
        return this.idProvee;
    }
    
    public void setIdProvee(int idProvee) {
        this.idProvee = idProvee;
    }

    
    @Column(name="nombre", length=60)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unresolved")
    public Set getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set proveedors) {
        this.proveedors = proveedors;
    }




}


