package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoCarreta generated by hbm2java
 */
@Entity
@Table(name="tipo_carreta"
    ,schema="public"
)
public class TipoCarreta  implements java.io.Serializable {


     private int idTipoCarreta;
     private String descripcion;
     private int peso;
     private Set carretas = new HashSet(0);

    public TipoCarreta() {
    }

	
    public TipoCarreta(int idTipoCarreta, String descripcion, int peso) {
        this.idTipoCarreta = idTipoCarreta;
        this.descripcion = descripcion;
        this.peso = peso;
    }
    public TipoCarreta(int idTipoCarreta, String descripcion, int peso, Set carretas) {
       this.idTipoCarreta = idTipoCarreta;
       this.descripcion = descripcion;
       this.peso = peso;
       this.carretas = carretas;
    }
   
     @Id 

    
    @Column(name="id_tipo_carreta", nullable=false)
    public int getIdTipoCarreta() {
        return this.idTipoCarreta;
    }
    
    public void setIdTipoCarreta(int idTipoCarreta) {
        this.idTipoCarreta = idTipoCarreta;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="peso", nullable=false)
    public int getPeso() {
        return this.peso;
    }
    
    public void setPeso(int peso) {
        this.peso = peso;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoCarreta")
    public Set getCarretas() {
        return this.carretas;
    }
    
    public void setCarretas(Set carretas) {
        this.carretas = carretas;
    }




}


