package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoViatico generated by hbm2java
 */
@Entity
@Table(name="tipo_viatico"
    ,schema="public"
)
public class TipoViatico  implements java.io.Serializable {


     private int idTipo;
     private String descripcion;
     private Set viaticos = new HashSet(0);

    public TipoViatico() {
    }

	
    public TipoViatico(int idTipo, String descripcion) {
        this.idTipo = idTipo;
        this.descripcion = descripcion;
    }
    public TipoViatico(int idTipo, String descripcion, Set viaticos) {
       this.idTipo = idTipo;
       this.descripcion = descripcion;
       this.viaticos = viaticos;
    }
   
     @Id 

    
    @Column(name="id_tipo", nullable=false)
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }

    
    @Column(name="descripcion", nullable=false, length=40)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoViatico")
    public Set getViaticos() {
        return this.viaticos;
    }
    
    public void setViaticos(Set viaticos) {
        this.viaticos = viaticos;
    }




}


