package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoCamion generated by hbm2java
 */
@Entity
@Table(name="tipo_camion"
    ,schema="public"
)
public class TipoCamion  implements java.io.Serializable {


     private int idTipoCamion;
     private String descripcion;
     private int peso;
     private Set camions = new HashSet(0);

    public TipoCamion() {
    }

	
    public TipoCamion(int idTipoCamion, String descripcion, int peso) {
        this.idTipoCamion = idTipoCamion;
        this.descripcion = descripcion;
        this.peso = peso;
    }
    public TipoCamion(int idTipoCamion, String descripcion, int peso, Set camions) {
       this.idTipoCamion = idTipoCamion;
       this.descripcion = descripcion;
       this.peso = peso;
       this.camions = camions;
    }
   
     @Id 

    
    @Column(name="id_tipo_camion", nullable=false)
    public int getIdTipoCamion() {
        return this.idTipoCamion;
    }
    
    public void setIdTipoCamion(int idTipoCamion) {
        this.idTipoCamion = idTipoCamion;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="peso", nullable=false)
    public int getPeso() {
        return this.peso;
    }
    
    public void setPeso(int peso) {
        this.peso = peso;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoCamion")
    public Set getCamions() {
        return this.camions;
    }
    
    public void setCamions(Set camions) {
        this.camions = camions;
    }




}


