package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoItem generated by hbm2java
 */
@Entity
@Table(name="tipo_item"
    ,schema="public"
)
public class TipoItem  implements java.io.Serializable {


     private int idTipo;
     private String descrip;
     private Set items = new HashSet(0);

    public TipoItem() {
    }

	
    public TipoItem(int idTipo, String descrip) {
        this.idTipo = idTipo;
        this.descrip = descrip;
    }
    public TipoItem(int idTipo, String descrip, Set items) {
       this.idTipo = idTipo;
       this.descrip = descrip;
       this.items = items;
    }
   
     @Id 

    
    @Column(name="id_tipo", nullable=false)
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }

    
    @Column(name="descrip", nullable=false, length=50)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoItem")
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


