package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Tolerancia generated by hbm2java
 */
@Entity
@Table(name="tolerancia"
    ,schema="public"
)
public class Tolerancia  implements java.io.Serializable {


     private int idTolerancia;
     private Cliente cliente;
     private double tolerancia;
     private String tipo;
     private Set viajes = new HashSet(0);

    public Tolerancia() {
    }

	
    public Tolerancia(Cliente cliente, double tolerancia, String tipo) {
        this.cliente = cliente;
        this.tolerancia = tolerancia;
        this.tipo = tipo;
    }
    public Tolerancia(Cliente cliente, double tolerancia, String tipo, Set viajes) {
       this.cliente = cliente;
       this.tolerancia = tolerancia;
       this.tipo = tipo;
       this.viajes = viajes;
    }
   
     @SequenceGenerator(name="generator", sequenceName="tolerancia_id_tolerancia_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_tolerancia", nullable=false)
    public int getIdTolerancia() {
        return this.idTolerancia;
    }
    
    public void setIdTolerancia(int idTolerancia) {
        this.idTolerancia = idTolerancia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_id_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="tolerancia", nullable=false, precision=17, scale=17)
    public double getTolerancia() {
        return this.tolerancia;
    }
    
    public void setTolerancia(double tolerancia) {
        this.tolerancia = tolerancia;
    }

    
    @Column(name="tipo", nullable=false, length=30)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tolerancia")
    public Set getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set viajes) {
        this.viajes = viajes;
    }




}


