package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * UnidadProvee generated by hbm2java
 */
@Entity
@Table(name="unidad_provee"
    ,schema="public"
)
public class UnidadProvee  implements java.io.Serializable {


     private int idUnidad;
     private ProveeCliente proveeCliente;
     private String nombre;
     private String telefono;
     private String descrip;
     private Set suministros = new HashSet(0);
     private Set precioSuministros = new HashSet(0);

    public UnidadProvee() {
    }

    public UnidadProvee(ProveeCliente proveeCliente, String nombre, String telefono, String descrip, Set suministros, Set precioSuministros) {
       this.proveeCliente = proveeCliente;
       this.nombre = nombre;
       this.telefono = telefono;
       this.descrip = descrip;
       this.suministros = suministros;
       this.precioSuministros = precioSuministros;
    }
   
     @SequenceGenerator(name="generator", sequenceName="unidad_provee_id_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_unidad", nullable=false)
    public int getIdUnidad() {
        return this.idUnidad;
    }
    
    public void setIdUnidad(int idUnidad) {
        this.idUnidad = idUnidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_proveecli")
    public ProveeCliente getProveeCliente() {
        return this.proveeCliente;
    }
    
    public void setProveeCliente(ProveeCliente proveeCliente) {
        this.proveeCliente = proveeCliente;
    }

    
    @Column(name="nombre", length=80)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="telefono", length=30)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="descrip", length=80)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadProvee")
    public Set getSuministros() {
        return this.suministros;
    }
    
    public void setSuministros(Set suministros) {
        this.suministros = suministros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadProvee")
    public Set getPrecioSuministros() {
        return this.precioSuministros;
    }
    
    public void setPrecioSuministros(Set precioSuministros) {
        this.precioSuministros = precioSuministros;
    }




}


