package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * UnidadDestino generated by hbm2java
 */
@Entity
@Table(name="unidad_destino"
    ,schema="public"
)
public class UnidadDestino  implements java.io.Serializable {


     private int idUnidadDestino;
     private String nombre;
     private String direccion;
     private String correo;
     private String descripcion;
     private Set precioFletes = new HashSet(0);
     private Set ordenDeCargas = new HashSet(0);

    public UnidadDestino() {
    }

	
    public UnidadDestino(String nombre, String direccion) {
        this.nombre = nombre;
        this.direccion = direccion;
    }
    public UnidadDestino(String nombre, String direccion, String correo, String descripcion, Set precioFletes, Set ordenDeCargas) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.correo = correo;
       this.descripcion = descripcion;
       this.precioFletes = precioFletes;
       this.ordenDeCargas = ordenDeCargas;
    }
   
     @SequenceGenerator(name="generator", sequenceName="unidad_destino_id_unidad_destino_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_unidad_destino", nullable=false)
    public int getIdUnidadDestino() {
        return this.idUnidadDestino;
    }
    
    public void setIdUnidadDestino(int idUnidadDestino) {
        this.idUnidadDestino = idUnidadDestino;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="direccion", nullable=false, length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="correo", length=50)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadDestino")
    public Set getPrecioFletes() {
        return this.precioFletes;
    }
    
    public void setPrecioFletes(Set precioFletes) {
        this.precioFletes = precioFletes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadDestino")
    public Set getOrdenDeCargas() {
        return this.ordenDeCargas;
    }
    
    public void setOrdenDeCargas(Set ordenDeCargas) {
        this.ordenDeCargas = ordenDeCargas;
    }




}


