package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ValeCombustible generated by hbm2java
 */
@Entity
@Table(name="vale_combustible"
    ,schema="public"
)
public class ValeCombustible  implements java.io.Serializable {


     private int idValeCombustible;
     private Camion camion;
     private OrdenDeCarga ordenDeCarga;
     private Proveedor proveedor;
     private TipoCombustible tipoCombustible;
     private Usuario usuario;
     private double litros;
     private double precioComb;
     private double montoTotal;
     private String descripcion;
     private Date fecha;
     private String estado;
     private double extras;
     private double montoComb;
     private double viatico;
     private Set combustibleContras = new HashSet(0);
     private Set combustibles = new HashSet(0);

    public ValeCombustible() {
    }

	
    public ValeCombustible(Camion camion, OrdenDeCarga ordenDeCarga, Proveedor proveedor, TipoCombustible tipoCombustible, Usuario usuario, double litros, double precioComb, double montoTotal, String descripcion, Date fecha, String estado, double extras, double montoComb, double viatico) {
        this.camion = camion;
        this.ordenDeCarga = ordenDeCarga;
        this.proveedor = proveedor;
        this.tipoCombustible = tipoCombustible;
        this.usuario = usuario;
        this.litros = litros;
        this.precioComb = precioComb;
        this.montoTotal = montoTotal;
        this.descripcion = descripcion;
        this.fecha = fecha;
        this.estado = estado;
        this.extras = extras;
        this.montoComb = montoComb;
        this.viatico = viatico;
    }
    public ValeCombustible(Camion camion, OrdenDeCarga ordenDeCarga, Proveedor proveedor, TipoCombustible tipoCombustible, Usuario usuario, double litros, double precioComb, double montoTotal, String descripcion, Date fecha, String estado, double extras, double montoComb, double viatico, Set combustibleContras, Set combustibles) {
       this.camion = camion;
       this.ordenDeCarga = ordenDeCarga;
       this.proveedor = proveedor;
       this.tipoCombustible = tipoCombustible;
       this.usuario = usuario;
       this.litros = litros;
       this.precioComb = precioComb;
       this.montoTotal = montoTotal;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.estado = estado;
       this.extras = extras;
       this.montoComb = montoComb;
       this.viatico = viatico;
       this.combustibleContras = combustibleContras;
       this.combustibles = combustibles;
    }
   
     @SequenceGenerator(name="generator", sequenceName="vale_combustible_id_vale_combustible_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_vale_combustible", nullable=false)
    public int getIdValeCombustible() {
        return this.idValeCombustible;
    }
    
    public void setIdValeCombustible(int idValeCombustible) {
        this.idValeCombustible = idValeCombustible;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="camion_chapa_camion", nullable=false)
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orden_de_carga_id_orden_de_carga", nullable=false)
    public OrdenDeCarga getOrdenDeCarga() {
        return this.ordenDeCarga;
    }
    
    public void setOrdenDeCarga(OrdenDeCarga ordenDeCarga) {
        this.ordenDeCarga = ordenDeCarga;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proveedor_id_proveedor", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_combustible_id_tipo_combustible", nullable=false)
    public TipoCombustible getTipoCombustible() {
        return this.tipoCombustible;
    }
    
    public void setTipoCombustible(TipoCombustible tipoCombustible) {
        this.tipoCombustible = tipoCombustible;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="litros", nullable=false, precision=17, scale=17)
    public double getLitros() {
        return this.litros;
    }
    
    public void setLitros(double litros) {
        this.litros = litros;
    }

    
    @Column(name="precio_comb", nullable=false, precision=17, scale=17)
    public double getPrecioComb() {
        return this.precioComb;
    }
    
    public void setPrecioComb(double precioComb) {
        this.precioComb = precioComb;
    }

    
    @Column(name="monto_total", nullable=false, precision=17, scale=17)
    public double getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(double montoTotal) {
        this.montoTotal = montoTotal;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="estado", nullable=false, length=15)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="extras", nullable=false, precision=17, scale=17)
    public double getExtras() {
        return this.extras;
    }
    
    public void setExtras(double extras) {
        this.extras = extras;
    }

    
    @Column(name="monto_comb", nullable=false, precision=17, scale=17)
    public double getMontoComb() {
        return this.montoComb;
    }
    
    public void setMontoComb(double montoComb) {
        this.montoComb = montoComb;
    }

    
    @Column(name="viatico", nullable=false, precision=17, scale=17)
    public double getViatico() {
        return this.viatico;
    }
    
    public void setViatico(double viatico) {
        this.viatico = viatico;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="valeCombustible")
    public Set getCombustibleContras() {
        return this.combustibleContras;
    }
    
    public void setCombustibleContras(Set combustibleContras) {
        this.combustibleContras = combustibleContras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="valeCombustible")
    public Set getCombustibles() {
        return this.combustibles;
    }
    
    public void setCombustibles(Set combustibles) {
        this.combustibles = combustibles;
    }




}


