package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ValeVarios generated by hbm2java
 */
@Entity
@Table(name="vale_varios"
    ,schema="public"
)
public class ValeVarios  implements java.io.Serializable {


     private int idValeVarios;
     private Camion camion;
     private ProveedorVarios proveedorVarios;
     private Usuario usuario;
     private Date fecha;
     private String descripcion;
     private double monto;
     private String estado;
     private Set varioses = new HashSet(0);

    public ValeVarios() {
    }

	
    public ValeVarios(Camion camion, ProveedorVarios proveedorVarios, Usuario usuario, Date fecha, String descripcion, double monto, String estado) {
        this.camion = camion;
        this.proveedorVarios = proveedorVarios;
        this.usuario = usuario;
        this.fecha = fecha;
        this.descripcion = descripcion;
        this.monto = monto;
        this.estado = estado;
    }
    public ValeVarios(Camion camion, ProveedorVarios proveedorVarios, Usuario usuario, Date fecha, String descripcion, double monto, String estado, Set varioses) {
       this.camion = camion;
       this.proveedorVarios = proveedorVarios;
       this.usuario = usuario;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.monto = monto;
       this.estado = estado;
       this.varioses = varioses;
    }
   
     @SequenceGenerator(name="generator", sequenceName="vale_varios_id_vale_varios_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_vale_varios", nullable=false)
    public int getIdValeVarios() {
        return this.idValeVarios;
    }
    
    public void setIdValeVarios(int idValeVarios) {
        this.idValeVarios = idValeVarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="camion_chapa_camion", nullable=false)
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proveedor_varios_id_proveedor_varios", nullable=false)
    public ProveedorVarios getProveedorVarios() {
        return this.proveedorVarios;
    }
    
    public void setProveedorVarios(ProveedorVarios proveedorVarios) {
        this.proveedorVarios = proveedorVarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="monto", nullable=false, precision=17, scale=17)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    
    @Column(name="estado", nullable=false, length=15)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="valeVarios")
    public Set getVarioses() {
        return this.varioses;
    }
    
    public void setVarioses(Set varioses) {
        this.varioses = varioses;
    }




}


