package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Varios generated by hbm2java
 */
@Entity
@Table(name="varios"
    ,schema="public"
)
public class Varios  implements java.io.Serializable {


     private int idVarios;
     private Usuario usuario;
     private ValeVarios valeVarios;
     private Date fecha;
     private double monto;
     private String descripcion;
     private String estadoCobro;
     private String estadoPago;
     private Set detallePagoVarioses = new HashSet(0);

    public Varios() {
    }

	
    public Varios(Usuario usuario, ValeVarios valeVarios, Date fecha, double monto, String descripcion, String estadoCobro, String estadoPago) {
        this.usuario = usuario;
        this.valeVarios = valeVarios;
        this.fecha = fecha;
        this.monto = monto;
        this.descripcion = descripcion;
        this.estadoCobro = estadoCobro;
        this.estadoPago = estadoPago;
    }
    public Varios(Usuario usuario, ValeVarios valeVarios, Date fecha, double monto, String descripcion, String estadoCobro, String estadoPago, Set detallePagoVarioses) {
       this.usuario = usuario;
       this.valeVarios = valeVarios;
       this.fecha = fecha;
       this.monto = monto;
       this.descripcion = descripcion;
       this.estadoCobro = estadoCobro;
       this.estadoPago = estadoPago;
       this.detallePagoVarioses = detallePagoVarioses;
    }
   
     @SequenceGenerator(name="generator", sequenceName="varios_id_varios_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_varios", nullable=false)
    public int getIdVarios() {
        return this.idVarios;
    }
    
    public void setIdVarios(int idVarios) {
        this.idVarios = idVarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vale_varios_id_vale_varios", nullable=false)
    public ValeVarios getValeVarios() {
        return this.valeVarios;
    }
    
    public void setValeVarios(ValeVarios valeVarios) {
        this.valeVarios = valeVarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="monto", nullable=false, precision=17, scale=17)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="estado_cobro", nullable=false, length=15)
    public String getEstadoCobro() {
        return this.estadoCobro;
    }
    
    public void setEstadoCobro(String estadoCobro) {
        this.estadoCobro = estadoCobro;
    }

    
    @Column(name="estado_pago", nullable=false, length=20)
    public String getEstadoPago() {
        return this.estadoPago;
    }
    
    public void setEstadoPago(String estadoPago) {
        this.estadoPago = estadoPago;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="varios")
    public Set getDetallePagoVarioses() {
        return this.detallePagoVarioses;
    }
    
    public void setDetallePagoVarioses(Set detallePagoVarioses) {
        this.detallePagoVarioses = detallePagoVarioses;
    }




}


