package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Viatico generated by hbm2java
 */
@Entity
@Table(name="viatico"
    ,schema="public"
)
public class Viatico  implements java.io.Serializable {


     private int idViatico;
     private Camion camion;
     private Chofer chofer;
     private OrdenDeCarga ordenDeCarga;
     private TipoViatico tipoViatico;
     private Usuario usuario;
     private double monto;
     private Date fecha;
     private String descripcion;
     private String estado;
     private Set viaticoContras = new HashSet(0);
     private Set combustibles = new HashSet(0);

    public Viatico() {
    }

	
    public Viatico(Camion camion, Chofer chofer, OrdenDeCarga ordenDeCarga, TipoViatico tipoViatico, Usuario usuario, double monto, Date fecha, String estado) {
        this.camion = camion;
        this.chofer = chofer;
        this.ordenDeCarga = ordenDeCarga;
        this.tipoViatico = tipoViatico;
        this.usuario = usuario;
        this.monto = monto;
        this.fecha = fecha;
        this.estado = estado;
    }
    public Viatico(Camion camion, Chofer chofer, OrdenDeCarga ordenDeCarga, TipoViatico tipoViatico, Usuario usuario, double monto, Date fecha, String descripcion, String estado, Set viaticoContras, Set combustibles) {
       this.camion = camion;
       this.chofer = chofer;
       this.ordenDeCarga = ordenDeCarga;
       this.tipoViatico = tipoViatico;
       this.usuario = usuario;
       this.monto = monto;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.estado = estado;
       this.viaticoContras = viaticoContras;
       this.combustibles = combustibles;
    }
   
     @SequenceGenerator(name="generator", sequenceName="viatico_id_viatico_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id_viatico", nullable=false)
    public int getIdViatico() {
        return this.idViatico;
    }
    
    public void setIdViatico(int idViatico) {
        this.idViatico = idViatico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="camion_chapa_camion", nullable=false)
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="chofer_id_chofer", nullable=false)
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orden_de_carga_id_orden_de_carga", nullable=false)
    public OrdenDeCarga getOrdenDeCarga() {
        return this.ordenDeCarga;
    }
    
    public void setOrdenDeCarga(OrdenDeCarga ordenDeCarga) {
        this.ordenDeCarga = ordenDeCarga;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_viatico_id_tipo", nullable=false)
    public TipoViatico getTipoViatico() {
        return this.tipoViatico;
    }
    
    public void setTipoViatico(TipoViatico tipoViatico) {
        this.tipoViatico = tipoViatico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="monto", nullable=false, precision=17, scale=17)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="estado", nullable=false, length=15)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="viatico")
    public Set getViaticoContras() {
        return this.viaticoContras;
    }
    
    public void setViaticoContras(Set viaticoContras) {
        this.viaticoContras = viaticoContras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="viatico")
    public Set getCombustibles() {
        return this.combustibles;
    }
    
    public void setCombustibles(Set combustibles) {
        this.combustibles = combustibles;
    }




}


