package model;
// Generated 22/10/2021 08:36:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ViaticoContra generated by hbm2java
 */
@Entity
@Table(name="viatico_contra"
    ,schema="public"
)
public class ViaticoContra  implements java.io.Serializable {


     private int id;
     private Contrasenha contrasenha;
     private Viatico viatico;

    public ViaticoContra() {
    }

    public ViaticoContra(Contrasenha contrasenha, Viatico viatico) {
       this.contrasenha = contrasenha;
       this.viatico = viatico;
    }
   
     @SequenceGenerator(name="generator", sequenceName="viatico_contra_id_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="contrasenha_id_contrasenha", nullable=false)
    public Contrasenha getContrasenha() {
        return this.contrasenha;
    }
    
    public void setContrasenha(Contrasenha contrasenha) {
        this.contrasenha = contrasenha;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="viatico_id_viatico", nullable=false)
    public Viatico getViatico() {
        return this.viatico;
    }
    
    public void setViatico(Viatico viatico) {
        this.viatico = viatico;
    }




}


